// SpacetimeClient.ts — GodotJS TypeScript node
// Bridges SpacetimeDB MainCloud ↔ GDScript (NetworkManager).
//
// Prerequisites:
//   npm install @clockworklabs/spacetimedb
//   spacetime generate --lang typescript --out-dir res://network/module_bindings
//
// Attach this file to a Node scene at res://scenes/network/spacetime_client.tscn
// NetworkManager instantiates that scene and connects to the signals below.

import { Node } from "godot";
import { GArray, GDictionary } from "godot";

// Module bindings generated by `spacetime generate` — import after running generate
// These types are forward-declared here so TypeScript compilation does not fail
// before the bindings are generated.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DbConn = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Identity = any;

const MAINCLOUD_URI  = "wss://maincloud.spacetimedb.com";
const LOCAL_URI      = "ws://localhost:3000";   // used during F-1 local testing
const MODULE_NAME    = "bataz";
const TOKEN_PATH     = "user://network_token.txt";
const USE_LOCAL      = false; // flip to true during F-1 local testing

// ── Signal names (all emitted to GDScript via emit_signal) ──────────────────
//
// Lifecycle:    connected | disconnected
// Lobby:        game_created(gameId, joinCode) | game_joined(gameId) | join_failed(reason)
// Placement:    placement_phase_started(player)
// Gameplay:     game_state_updated(state_dict) | board_sync(pawns_array)
//               pawn_moved(fc, fr, tc, tr) | pawn_removed(col, row, team)
//               hand_updated(player, hand_array) | attack_declared(data_dict)
//               movement_rolled(points) | game_over(winner) | event_logged(text)

export default class SpacetimeClient extends Node {

    private _conn: DbConn | null = null;
    private _myIdentity: Identity | null = null;
    private _gameId: number = -1;
    private _gamePlayer1Identity: Identity | null = null;
    private _lastKnownGame: Record<string, unknown> | null = null;
    private _lastKnownPawns: Map<number, Record<string, unknown>> = new Map();

    // ── Godot lifecycle ────────────────────────────────────────────────────

    _ready(): void {
        // Register all signals so GDScript can connect to them before connect_to_server() is called
        const sigs = [
            "connected", "disconnected",
            "game_created", "game_joined", "join_failed",
            "placement_phase_started",
            "game_state_updated", "board_sync",
            "pawn_moved", "pawn_removed",
            "hand_updated", "attack_declared",
            "movement_rolled", "game_over",
            "event_logged",
        ];
        for (const s of sigs) {
            // add_user_signal allows GDScript to connect before the signal is first emitted
            this.add_user_signal(s);
        }
    }

    // ── Public API called by NetworkManager ───────────────────────────────

    connect_to_server(): void {
        // Lazy-import module bindings (generated by spacetime generate)
        // Using dynamic require so the file can be compiled before bindings exist
        // eslint-disable-next-line @typescript-eslint/no-var-requires
        let DbConnection: typeof import("./module_bindings").DbConnection;
        try {
            // eslint-disable-next-line @typescript-eslint/no-var-requires
            DbConnection = require("./module_bindings").DbConnection;
        } catch {
            console.error("[SpacetimeClient] module_bindings not found. Run: spacetime generate --lang typescript --out-dir res://network/module_bindings");
            return;
        }

        const savedToken = this._loadToken();
        const uri = USE_LOCAL ? LOCAL_URI : MAINCLOUD_URI;

        const builder = DbConnection.builder()
            .withUri(uri)
            .withModuleName(MODULE_NAME);

        if (savedToken) {
            builder.withCredentials({ token: savedToken });
        }

        builder.onConnect((conn: DbConn, identity: Identity, token: string) => {
            this._conn        = conn;
            this._myIdentity  = identity;
            this._saveToken(token);
            this._registerTableCallbacks();
            conn.subscriptionBuilder().subscribeToAllTables();
            this.emit_signal("connected");
        });

        builder.onDisconnect(() => {
            this._conn = null;
            this.emit_signal("disconnected");
        });

        builder.onConnectError((_conn: DbConn, err: Error) => {
            console.error("[SpacetimeClient] connect error:", err);
            this.emit_signal("disconnected");
        });

        builder.build();
    }

    // ── Lobby ──────────────────────────────────────────────────────────────

    create_game(): void {
        this._conn?.reducers.createGame();
    }

    join_game(joinCode: string): void {
        this._conn?.reducers.joinGame(joinCode);
    }

    // ── Placement ─────────────────────────────────────────────────────────

    place_pawn(gameId: number, col: number, row: number): void {
        this._conn?.reducers.placePawn(gameId, col, row);
    }

    remove_placement_pawn(gameId: number, col: number, row: number): void {
        this._conn?.reducers.removePlacementPawn(gameId, col, row);
    }

    confirm_placement(gameId: number): void {
        this._conn?.reducers.confirmPlacement(gameId);
    }

    // ── Gameplay ──────────────────────────────────────────────────────────

    play_card(gameId: number, slotIndex: number): void {
        this._conn?.reducers.playCard(gameId, slotIndex);
    }

    discard_and_pass(gameId: number): void {
        this._conn?.reducers.discardAndPass(gameId);
    }

    move_pawn(gameId: number, fromCol: number, fromRow: number, toCol: number, toRow: number): void {
        this._conn?.reducers.movePawn(gameId, fromCol, fromRow, toCol, toRow);
    }

    done_moving(gameId: number): void {
        this._conn?.reducers.doneMoving(gameId);
    }

    declare_attack(gameId: number, attackerCol: number, attackerRow: number, defenderCol: number, defenderRow: number): void {
        this._conn?.reducers.declareAttack(gameId, attackerCol, attackerRow, defenderCol, defenderRow);
    }

    play_defense(gameId: number, slotIndex: number): void {
        this._conn?.reducers.playDefense(gameId, slotIndex);
    }

    pass_defense(gameId: number): void {
        this._conn?.reducers.passDefense(gameId);
    }

    end_turn(gameId: number): void {
        this._conn?.reducers.endTurn(gameId);
    }

    // ── Utility ───────────────────────────────────────────────────────────

    get_my_player_slot(): number {
        if (!this._conn || !this._myIdentity || !this._lastKnownGame) return 0;
        const g = this._lastKnownGame;
        if (this._myIdentity === g["player1"]) return 1;
        if (this._myIdentity === g["player2"]) return 2;
        return 0;
    }

    get_game_id(): number {
        return this._gameId;
    }

    // ── Table change callbacks ────────────────────────────────────────────

    private _registerTableCallbacks(): void {
        if (!this._conn) return;
        const db = this._conn.db;

        // ── game table ──────────────────────────────────────────────────
        db.game.onInsert((_ctx: unknown, game: Record<string, unknown>) => {
            const sender: Identity = (this._conn as any).identity;
            if (game["player1"] === sender) {
                this._gameId              = game["gameId"] as number;
                this._lastKnownGame       = game;
                this._gamePlayer1Identity = game["player1"] as Identity;
                this.emit_signal("game_created",
                    game["gameId"] as number,
                    game["joinCode"] as string);
            }
        });

        db.game.onUpdate((_ctx: unknown, oldGame: Record<string, unknown>, newGame: Record<string, unknown>) => {
            if ((newGame["gameId"] as number) !== this._gameId) return;

            const prevState  = oldGame["state"]  as string;
            const nextState  = newGame["state"]  as string;
            const prevPhase  = oldGame["phase"]  as string;
            const nextPhase  = newGame["phase"]  as string;

            this._lastKnownGame = newGame;

            // game_joined: fires on both clients when Player2 joins (state: WAITING → PLACEMENT_P1)
            if (prevState === "WAITING" && nextState === "PLACEMENT_P1") {
                this.emit_signal("game_joined", newGame["gameId"] as number);
            }

            // placement_phase_started
            if (nextState === "PLACEMENT_P1" && prevState !== "PLACEMENT_P1") {
                this.emit_signal("placement_phase_started", 1);
            } else if (nextState === "PLACEMENT_P2" && prevState !== "PLACEMENT_P2") {
                this.emit_signal("placement_phase_started", 2);
            }

            // movement rolled: MovementPoints set + phase → RESOLVE_MOVEMENT
            if (nextPhase === "RESOLVE_MOVEMENT" && prevPhase !== "RESOLVE_MOVEMENT") {
                this.emit_signal("movement_rolled", newGame["movementPoints"] as number);
            }

            // game_over
            if (nextState === "GAME_OVER" && prevState !== "GAME_OVER") {
                this.emit_signal("game_over", newGame["winner"] as number);
            }

            // General state update (current_player, phase, movement_points, state, winner)
            const stateDict = GDictionary.create({
                current_player:   newGame["currentPlayer"],
                phase:            newGame["phase"],
                movement_points:  newGame["movementPoints"],
                state:            newGame["state"],
                winner:           newGame["winner"],
            });
            this.emit_signal("game_state_updated", stateDict);
        });

        // ── pawn table ──────────────────────────────────────────────────
        db.pawn.onInsert((_ctx: unknown, pawn: Record<string, unknown>) => {
            if ((pawn["gameId"] as number) !== this._gameId) return;
            this._lastKnownPawns.set(pawn["pawnId"] as number, pawn);
            this._tryEmitBoardSync();
        });

        db.pawn.onUpdate((_ctx: unknown, oldPawn: Record<string, unknown>, newPawn: Record<string, unknown>) => {
            if ((newPawn["gameId"] as number) !== this._gameId) return;
            this._lastKnownPawns.set(newPawn["pawnId"] as number, newPawn);

            // placed false→true triggers board_sync (all pawns active after placement)
            if (!(oldPawn["placed"] as boolean) && (newPawn["placed"] as boolean)) {
                this._tryEmitBoardSync();
                return;
            }

            // position changed → pawn_moved
            if (oldPawn["col"] !== newPawn["col"] || oldPawn["row"] !== newPawn["row"]) {
                this.emit_signal("pawn_moved",
                    oldPawn["col"] as number, oldPawn["row"] as number,
                    newPawn["col"] as number, newPawn["row"] as number);
            }
        });

        db.pawn.onDelete((_ctx: unknown, pawn: Record<string, unknown>) => {
            if ((pawn["gameId"] as number) !== this._gameId) return;
            this._lastKnownPawns.delete(pawn["pawnId"] as number);
            this.emit_signal("pawn_removed",
                pawn["col"] as number, pawn["row"] as number, pawn["team"] as number);
        });

        // ── card_hand table ─────────────────────────────────────────────
        db.cardHand.onInsert((_ctx: unknown, _card: Record<string, unknown>) => {
            if ((_card["gameId"] as number) !== this._gameId) return;
            this._rebuildAndEmitHand(_card["player"] as number);
        });

        db.cardHand.onDelete((_ctx: unknown, _card: Record<string, unknown>) => {
            if ((_card["gameId"] as number) !== this._gameId) return;
            this._rebuildAndEmitHand(_card["player"] as number);
        });

        // ── pending_attack table ────────────────────────────────────────
        db.pendingAttack.onInsert((_ctx: unknown, attack: Record<string, unknown>) => {
            if ((attack["gameId"] as number) !== this._gameId) return;
            const attackDict = GDictionary.create({
                attacker_col: attack["attackerCol"],
                attacker_row: attack["attackerRow"],
                defender_col: attack["defenderCol"],
                defender_row: attack["defenderRow"],
                attack_roll:  attack["attackRoll"],
                die_sides:    attack["dieSides"],
                die_label:    attack["dieLabel"],
            });
            this.emit_signal("attack_declared", attackDict);
        });

        // ── event_log table ─────────────────────────────────────────────
        db.eventLog.onInsert((_ctx: unknown, log: Record<string, unknown>) => {
            if ((log["gameId"] as number) !== this._gameId) return;
            this.emit_signal("event_logged", log["text"] as string);
        });

        // ── reducer callbacks (for error feedback) ─────────────────────
        this._conn.reducers.onCreateGame((_ctx: unknown, result: string) => {
            if (result !== "committed") {
                this.emit_signal("join_failed", `CreateGame failed: ${result}`);
            }
        });

        this._conn.reducers.onJoinGame((_ctx: unknown, result: string) => {
            if (result !== "committed") {
                this.emit_signal("join_failed", `JoinGame failed: ${result}`);
            }
        });
    }

    // ── Private helpers ───────────────────────────────────────────────────

    private _tryEmitBoardSync(): void {
        // Emit board_sync once all pawns have Placed=true (both teams ready)
        const allPawns = Array.from(this._lastKnownPawns.values())
            .filter(p => (p["gameId"] as number) === this._gameId);
        const allPlaced = allPawns.length === 16 && allPawns.every(p => p["placed"] as boolean);
        if (!allPlaced) return;

        const pawnsArray = GArray.create(allPawns.map(p => GDictionary.create({
            col:    p["col"],
            row:    p["row"],
            team:   p["team"],
            pawn_id: p["pawnId"],
        })));
        this.emit_signal("board_sync", pawnsArray);
    }

    private _rebuildAndEmitHand(player: number): void {
        if (!this._conn) return;
        const hand = Array.from(this._conn.db.cardHand.iter())
            .filter((c: Record<string, unknown>) =>
                (c["gameId"] as number) === this._gameId && (c["player"] as number) === player)
            .sort((a: Record<string, unknown>, b: Record<string, unknown>) =>
                (a["slotIndex"] as number) - (b["slotIndex"] as number))
            .map((c: Record<string, unknown>) => c["cardType"] as string);

        const gdHand = GArray.create(hand);
        this.emit_signal("hand_updated", player, gdHand);
    }

    private _loadToken(): string | null {
        try {
            const fa = (globalThis as any).FileAccess;
            if (fa && fa.file_exists(TOKEN_PATH)) {
                const f = fa.open(TOKEN_PATH, 1); // FileAccess.READ = 1
                const t = f.get_as_text();
                f.close();
                return t.trim() || null;
            }
        } catch { /* not critical */ }
        return null;
    }

    private _saveToken(token: string): void {
        try {
            const fa = (globalThis as any).FileAccess;
            if (fa) {
                const f = fa.open(TOKEN_PATH, 2); // FileAccess.WRITE = 2
                f.store_string(token);
                f.close();
            }
        } catch { /* not critical */ }
    }
}
